# Generated by Django 3.1.6 on 2021-03-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210329_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=5)),
                ('suggest', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
                ('desc', models.CharField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
